(function() {var implementors = {};
implementors["chunky"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"chunky/struct.ArenaIndex.html\" title=\"struct chunky::ArenaIndex\">ArenaIndex</a>",synthetic:false,types:["chunky::ArenaIndex"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"chunky/struct.MultiArenaIndex.html\" title=\"struct chunky::MultiArenaIndex\">MultiArenaIndex</a>",synthetic:false,types:["chunky::MultiArenaIndex"]},];
implementors["descartes"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"descartes/struct.Circle.html\" title=\"struct descartes::Circle\">Circle</a>",synthetic:false,types:["descartes::curves::Circle"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"descartes/struct.Line.html\" title=\"struct descartes::Line\">Line</a>",synthetic:false,types:["descartes::curves::Line"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"descartes/struct.Segment.html\" title=\"struct descartes::Segment\">Segment</a>",synthetic:false,types:["descartes::curves::Segment"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"descartes/struct.Intersection.html\" title=\"struct descartes::Intersection\">Intersection</a>",synthetic:false,types:["descartes::intersect::Intersection"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"descartes/struct.BoundingBox.html\" title=\"struct descartes::BoundingBox\">BoundingBox</a>",synthetic:false,types:["descartes::BoundingBox"]},];
implementors["kay"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"kay/struct.MachineID.html\" title=\"struct kay::MachineID\">MachineID</a>",synthetic:false,types:["kay::id::MachineID"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"kay/struct.RawID.html\" title=\"struct kay::RawID\">RawID</a>",synthetic:false,types:["kay::id::RawID"]},];
implementors["kay_codegen"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"kay_codegen/enum.HandlerType.html\" title=\"enum kay_codegen::HandlerType\">HandlerType</a>",synthetic:false,types:["kay_codegen::HandlerType"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
