(function() {var implementors = {};
implementors["compact"] = [{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"compact/trait.Compact.html\" title=\"trait compact::Compact\">Compact</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a>, A:&nbsp;<a class=\"trait\" href=\"allocators/trait.Allocator.html\" title=\"trait allocators::Allocator\">Allocator</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"compact/struct.CVec.html\" title=\"struct compact::CVec\">CompactVec</a>&lt;T, A&gt;",synthetic:false,types:["compact::compact_vec::CompactVec"]},];
implementors["descartes"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"descartes/struct.Circle.html\" title=\"struct descartes::Circle\">Circle</a>",synthetic:false,types:["descartes::curves::Circle"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"descartes/struct.Line.html\" title=\"struct descartes::Line\">Line</a>",synthetic:false,types:["descartes::curves::Line"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"descartes/struct.Segment.html\" title=\"struct descartes::Segment\">Segment</a>",synthetic:false,types:["descartes::curves::Segment"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"descartes/struct.Path.html\" title=\"struct descartes::Path\">Path</a>",synthetic:false,types:["descartes::path::Path"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"descartes/struct.Intersection.html\" title=\"struct descartes::Intersection\">Intersection</a>",synthetic:false,types:["descartes::intersect::Intersection"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"descartes/enum.IntersectionResult.html\" title=\"enum descartes::IntersectionResult\">IntersectionResult</a>",synthetic:false,types:["descartes::intersect::IntersectionResult"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"descartes/struct.UnclosedPathError.html\" title=\"struct descartes::UnclosedPathError\">UnclosedPathError</a>",synthetic:false,types:["descartes::areas::UnclosedPathError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"descartes/struct.BoundaryPiece.html\" title=\"struct descartes::BoundaryPiece\">BoundaryPiece</a>",synthetic:false,types:["descartes::areas::BoundaryPiece"]},];
implementors["kay"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"kay/struct.MachineID.html\" title=\"struct kay::MachineID\">MachineID</a>",synthetic:false,types:["kay::id::MachineID"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"kay/struct.RawID.html\" title=\"struct kay::RawID\">RawID</a>",synthetic:false,types:["kay::id::RawID"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
