(function() {var implementors = {};
implementors["descartes"] = [{text:"impl <a class=\"trait\" href=\"compact/compact/trait.Compact.html\" title=\"trait compact::compact::Compact\">Compact</a> for <a class=\"struct\" href=\"descartes/struct.Path.html\" title=\"struct descartes::Path\">Path</a>",synthetic:false,types:["descartes::path::Path"]},{text:"impl <a class=\"trait\" href=\"compact/compact/trait.Compact.html\" title=\"trait compact::compact::Compact\">Compact</a> for <a class=\"struct\" href=\"descartes/struct.PrimitiveArea.html\" title=\"struct descartes::PrimitiveArea\">PrimitiveArea</a>",synthetic:false,types:["descartes::areas::PrimitiveArea"]},{text:"impl <a class=\"trait\" href=\"compact/compact/trait.Compact.html\" title=\"trait compact::compact::Compact\">Compact</a> for <a class=\"struct\" href=\"descartes/struct.Area.html\" title=\"struct descartes::Area\">Area</a>",synthetic:false,types:["descartes::areas::Area"]},{text:"impl <a class=\"trait\" href=\"compact/compact/trait.Compact.html\" title=\"trait compact::compact::Compact\">Compact</a> for <a class=\"struct\" href=\"descartes/struct.BoundaryPiece.html\" title=\"struct descartes::BoundaryPiece\">BoundaryPiece</a>",synthetic:false,types:["descartes::areas::BoundaryPiece"]},{text:"impl <a class=\"trait\" href=\"compact/compact/trait.Compact.html\" title=\"trait compact::compact::Compact\">Compact</a> for <a class=\"struct\" href=\"descartes/struct.AreaSplitResult.html\" title=\"struct descartes::AreaSplitResult\">AreaSplitResult</a>",synthetic:false,types:["descartes::areas::AreaSplitResult"]},{text:"impl <a class=\"trait\" href=\"compact/compact/trait.Compact.html\" title=\"trait compact::compact::Compact\">Compact</a> for <a class=\"struct\" href=\"descartes/struct.Band.html\" title=\"struct descartes::Band\">Band</a>",synthetic:false,types:["descartes::areas::Band"]},];
implementors["kay"] = [{text:"impl&lt;M:&nbsp;<a class=\"trait\" href=\"kay/trait.Message.html\" title=\"trait kay::Message\">Message</a>&gt; <a class=\"trait\" href=\"compact/compact/trait.Compact.html\" title=\"trait compact::compact::Compact\">Compact</a> for <a class=\"struct\" href=\"kay/struct.Packet.html\" title=\"struct kay::Packet\">Packet</a>&lt;M&gt;",synthetic:false,types:["kay::messaging::Packet"]},{text:"impl&lt;T&gt; <a class=\"trait\" href=\"compact/compact/trait.Compact.html\" title=\"trait compact::compact::Compact\">Compact</a> for <a class=\"struct\" href=\"kay/struct.External.html\" title=\"struct kay::External\">External</a>&lt;T&gt;",synthetic:false,types:["kay::external::External"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
